vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        posts_images:
           uri_prefix: /image/uploads/posts
           upload_destination: '%kernel.project_dir%/public/image/uploads/posts'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

        users_images:
           uri_prefix: /image/uploads/users
           upload_destination: '%kernel.project_dir%/public/image/uploads/users'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true